In [29]:
import numpy as np

# Create Arrays

In [207]:
# Create 1 dimensional array (vector)
np.array([1,2,3]) # Create vector as a row

array([1, 2, 3])

In [208]:
np.array([[1],[2],[3]]) #Create vector as a column


array([[1],
       [2],
       [3]])

In [211]:
np.array([(1,2,3),(4,5,6)]) # Two dimensional array

array([[1, 2, 3],
       [4, 5, 6]])

In [212]:
from scipy import sparse
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
# Create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


In [215]:
# Create  1d array of zeros, length 3
np.zeros(3) 

array([0., 0., 0.])

In [216]:
# 2x3 array of zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [217]:
# Create array of ones, 3x4 (3 rows, 4 columns)
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [218]:
#  5x5 array of 0 with 1 on diagonal (Identity matrix)
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [219]:
# Array of 6 evenly divided values from 0 to 100
np.linspace(0,100,6)

array([  0.,  20.,  40.,  60.,  80., 100.])

In [220]:
# Array of values from 0 to less than 10 with step 3 
np.arange(0,10,3)

array([0, 3, 6, 9])

In [221]:
# 2x3 array with all values 5
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [223]:
# 2x3 array of random floats between 0–1
np.random.rand(2,3)

array([[0.37174775, 0.59954596, 0.50488967],
       [0.22703386, 0.59914441, 0.68547572]])

In [226]:
# 2x3 array of random floats between 0–100
np.random.rand(2,3)*100

array([[23.17345972, 98.62743214, 21.40831291],
       [87.08603104, 84.23376262, 63.90231179]])

In [227]:
# 2x3 array with random ints between 0–4
np.random.randint(5,size=(2,3))

array([[4, 2, 4],
       [3, 3, 3]])

# Array shape manipulations

In [229]:
arr = np.array([(1,2,3),(4,5,6)])
arr.shape # Returns dimensions of arr (rows,columns)

(2, 3)

In [232]:
arr_to_list = arr.tolist() # Convert arr to a Python list
np.array(arr_to_list) # Convert list to array

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr.size # Return number of elements in arr
len(arr) #Length of arrayarr.ndim # Number of array dimension
arr.dtype # Return type of elements in arr
arr.dtype.name # Name of data type
arr.astype(int) # Convert an array to a different type
arr.astype(dtype) # Convert arr elements to type dtype
np.info(np.eye) # View documentation for np.eye

In [234]:
# Sort
oned_arr = np.array([3,8,5,1])
np.sort(oned_arr)
arr = np.array([[5, 4, 6, 8],
                [1, 2, 4, 8],
                [1, 5, 2, 4]])
# sort each column of arr
np.sort(arr, axis=0)

# sort each row of X
np.sort(arr, axis=1)

array([[4, 5, 6, 8],
       [1, 2, 4, 8],
       [1, 2, 4, 5]])

In [237]:
# Reshaping
arr1 = np.arange(1, 11)  # numbers 1 to 10
print(arr1.shape) # Prints a tuple for the one dimension.

arr1_2d = arr1.reshape(2, 5)
print(arr1_2d)

arr1.reshape(2, 5)
arr1.reshape(-1, 5)  # same as above: arr1.reshape(2, 5)
arr1.reshape(2, -1)  # same as above: arr1.reshape(2, 5)


(10,)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [239]:
# Transpose
arr1_2d.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [241]:
# Flattening a Matrix
arr1_2d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [243]:
# Resize arr1_2d to 3 rows, 4 columns 
np.resize(arr1_2d, (3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10,  1,  2]])

In [245]:
# Invert
matrix = np.array([[1, 2],
                   [3, 4]])
# Calculate inverse of matrix
np.linalg.inv(matrix)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# Numerical Operations

In [247]:
arr = np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2]])
np.trace(arr)

6

In [249]:
# Determinant
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])
# Return determinant of matrix
np.linalg.det(matrix)

0.0

In [251]:
# Rank of a matrix
matrix = np.array([[1, 1, 3],
                   [1, 2, 4],
                   [1, 3, 0]])
# Return matrix rank
np.linalg.matrix_rank(matrix)

3

In [253]:
# Eigenvalues and Eigenvectors
matrix = np.array([[0, 1, 2],
                   [3, 4, 5],
                   [6, 7, 8]])
# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

In [256]:
# Scalar Operations
new_arr = np.arange(1,10)

# Add 1 to each array element
np.add(new_arr,1)

np.subtract(arr,2) # Subtract 2 from each array element
np.multiply(arr,3) # Multiply each array element by 3
np.divide(arr,4) # Divide each array element by 4 (returns np.nan for division by zero)
np.power(arr,5) # Raise each array element to the 5th power

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Matrics  Operations
np.add(arr1,arr2) # Elementwise add arr2 to arr1
np.subtract(arr1,arr2) # Elementwise subtract arr2 from arr1
np.multiply(arr1,arr2) # Elementwise multiply arr1 by arr2
np.divide(arr1,arr2) # Elementwise divide arr1 by arr2
np.power(arr1,arr2) # Elementwise raise arr1 raised to the power of arr2
np.array_equal(arr1,arr2) # Returns True if the arrays have the same elements and shape

In [ ]:
np.sqrt(arr) # Square root of each element in the array
np.sin(arr) # Sine of each element in the array
np.log(arr) # Natural log of each element in the array
np.abs(arr) # Absolute value of each element in the array
np.ceil(arr) # Rounds up to the nearest int
np.floor(arr) # Rounds down to the nearest int
np.round(arr) # Rounds to the nearest int

# Array Manipulation Routines

In [ ]:
# Adding/removing Elements
np.append ([0, 1, 2], [[3, 4, 5], [6, 7, 8]])
np.append([[0, 1, 2], [3, 4, 5]],[[6, 7, 8]], axis=0)
np.insert(arr,2,10) # Inserts 10 into arr before index 2
np.delete(arr,2,axis=0) # Deletes row on index 2 of arr
np.delete(arr,3,axis=1) # Deletes column on index 3 of arr

In [ ]:
# Koin arrays
# Adds arr2 as rows to the end of arr1
arr = np.concatenate((arr1, arr2), axis=0)
# Adds arr2 as columns to end of arr1
arr = np.concatenate((arr1,arr2),axis=1)


In [ ]:
# Splitting NumPy Arrays
# Splits arr into 4 sub-arrays
newarr = np.array_split(arr, 4) 

# Splits arr horizontally on the 2nd index
newarr = np.hsplit(arr, 2)

In [ ]:
# Selecting elements
user_name = np.array(['Katie','Bob','Scott','Liz','Sam'])
articles = np.array([100, 38, 91, 7, 25])
user_name[4] # Returns the element at index 4

articles[3] = 17 # Assigns array element on index 1 the value 4

user_name[0:3] # Returns the elements at indices 0,1,2

user_name[:2] # Returns the elements at indices 0,1

articles<50 # Returns an array with boolean values

articles[articles < 50] # Returns the element values
array([38,  7, 25])
# Returns the user_name that read more than 50 articles but less than 100 articles
user_name[(articles < 100 ) & (articles >50)]

# Multi-dimensinal arrays
arr[2,5] # Returns the 2D array element on index [2][5]
arr[1,3]=10 # Assigns array element on index [1][3] the value 10
arr[0:3] # Returns rows 0,1,2
arr[0:3,4] # Returns the elements on rows 0,1,2 at column 4
arr[:2] # Returns returns rows 0,1
arr[:,1] # Returns the elements at index 1 on all rows

# Statistical Operations

In [ ]:
np.mean(arr,axis=0) # Returns mean along specific axis
arr.sum() # Returns sum of arr
arr.min() # Returns minimum value of arr
arr.max(axis=0) # Returns maximum value of specific axis
b.cumsum(axis=1) #Cumulative sum of the elements
np.var(arr) # Returns the variance of array
np.std(arr,axis=1) # Returns the standard deviation of specific axis
arr.corrcoef() # Returns correlation coefficient of array